imap <F5> <Esc>:w<CR>:!clear;python3 %<CR>
set backspace=indent,eol,start
set expandtab           " enter spaces when tab is pressed
set textwidth=120       " break lines when line length increases
set tabstop=4           " use 4 spaces to represent tab
set softtabstop=4
set shiftwidth=4        " number of spaces to use for auto indent
set autoindent          " copy indent from current line when starting a new line
set smartindent
set smarttab
set expandtab
set number
set backspace=indent,eol,start
set ruler                           " show line and column number
syntax on               " syntax highlighting
set showcmd             " show (partial) command in status line
filetype indent plugin on
filetype indent on
inoremap ( ()<ESC>i
inoremap " ""<ESC>i
inoremap ' ''<ESC>i
inoremap { {<Cr>}<Esc>O

